---
- src: "git@github.com:AlexeySetevoi/ansible-clickhouse.git"
  scm: git
  version: "1.13"
  name: clickhouse

- src: "git@github.com:zis-git/vector-role.git"
  scm: git
  version: "main"
  name: vector-role

- src: "git@github.com:zis-git/lighthouse-role.git"
  scm: git
  version: "main"
  name: lighthouse-role
